// File: lib/firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// This file is automatically generated by the `flutterfire configure` command.
// Do not directly edit this file.

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyDaLrFxDYm6AvKH-N0aeOGdCRohw6bRoXE',
    appId: '1:743207245622:android:2355591cdc117fba7d8597',
    messagingSenderId: '743207245622',
    projectId: 'meditrack-8dc24',
  );
}
